### ISSUE TITLE
way to pin a color to a window

### ISSUE THREAD

**Issue by kurktchiev** [Determinant/tmux-colortag#2]
So i like having specific colors on my default window setup, but this creates random colors on all new windows created in the session. 

I would like to create 3-4 windows with a specific color, and any new window to be non colored unless i tell it to be. Is that possible?

**Comment by Determinant** [comment]
It is possible to specify a specific color for a tab either by index (the tab number), or by name (the tab label). See here: https://github.com/Determinant/tmux-colortag#customization
But if I understand it correctly, you also would like a switch to turn of the auto-color functionality so it won't get too messy. Is that the case? I can add it if so.
